name: cutqc_new
channels:
  - gurobi
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1
  - backcall=0.2.0
  - ca-certificates
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - gurobi=11.0.2
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.8.19
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - dill==0.3.8
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - gast==0.4.0
      - google-auth==2.30.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - idna==3.7
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - keras==2.13.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pbr==6.0.0
      - pillow==10.3.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydot==2.0.0
      - pylatexenc==2.10
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - qiskit==1.1.1
      - qiskit-aer==0.14.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - rustworkx==0.15.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - stevedore==5.2.0
      - symengine==0.11.0
      - sympy==1.12.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - typing-extensions==4.5.0
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.16.0